name: publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
        
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v3
      with:
        node-version: 22.x
        cache: 'npm'
    
    - name: Build
      run: |
        npm ci
        npm run build

    - name: Publish
      run: npm publish
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
